allmeele = [
    {'name': 'Axe', 'sell': 3000},
    {'name': 'Baseball Bat', 'sell': 130},
    {'name': 'Bo Staff', 'sell': 300},
    {'name': 'Bone Saw', 'sell': 800},
    {'name': 'Butterfly Knife', 'sell': 1200},
    {'name': 'Chain Whip', 'sell': 2000},
    {'name': 'Chainsaw', 'sell': 11500},
    {'name': 'Claymore Sword', 'sell': 75000},
    {'name': 'Cricket Bat', 'sell': 10000},
    {'name': 'Crowbar', 'sell': 250},
    {'name': 'Dagger', 'sell': 1500},
    {'name': 'Diamond Bladed Knife', 'sell': 800000},
    {'name': 'Frying Pan', 'sell': 300},
    {'name': 'Golf Club', 'sell': 2150},
    {'name': 'Guandao', 'sell': 150000},
    {'name': 'Hammer', 'sell': 50},
    {'name': 'Ice Pick', 'sell': 23000},
    {'name': 'Kama', 'sell': 40000},
    {'name': 'Katana', 'sell': 13000},
    {'name': 'Kitchen Knife', 'sell': 1000},
    {'name': 'Knuckle Dusters', 'sell': 500},
    {'name': 'Kodachi', 'sell': 80000},
    {'name': 'Lead Pipe', 'sell': 100},
    {'name': 'Leather Bullwhip', 'sell': 750},
    {'name': 'Macana', 'sell': 80000},
    {'name': 'Metal Nunchaku', 'sell': 300000},
    {'name': 'Ninja Claws', 'sell': 5000},
    {'name': 'Pen Knife', 'sell': 750},
    {'name': 'Sai', 'sell': 700},
    {'name': 'Samurai Sword', 'sell': 53000},
    {'name': 'Scimitar', 'sell': 5400},
    {'name': 'Spear', 'sell': 400},
    {'name': 'Swiss Army Knife', 'sell': 2000},
    {'name': 'Twin Tiger Hooks', 'sell': 40000},
    {'name': 'Wooden Nunchaku', 'sell': 4000},
    {'name': 'Wushu Double Axes', 'sell': 60000},
    ]